core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('user/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
]

crm/urls.py
from django.urls import path

from crm import views

app_name = 'crm'

urlpatterns = [
    path('customer/form_communication/', views.get_form_communication,
         name='get_form_communication'),
    path('customer/<int:pk>/close_customer/', views.close_customer,
         name='crm_close_customer'),
    path('customer/<int:pk>/', views.CustomerDetail.as_view(),
         name='crm_customer_detail'),
    path('customer/<int:pk>/edit/', views.customer_edit,
         name='crm_customer_edit'),
    path('customer/<int:pk>/address/edit/', views.address_edit,
         name='crm_address_edit'),
    # path('customer-filter/', views.customer_list_filter, name='customer-filter'),
    path('order/<int:pk>/', views.OrderDetail.as_view(),
         name='crm_order_detail'),
    path('orders/product/<int:pk>/', views.ProductDetail.as_view(), name='crm_product_detail'),
    path('tasks/start/<int:pk>/<int:cust_pk>/<slug:object>/', views.start_task,
         name='start_task'),
    path('tasks/done/<int:cust_pk>/<int:pk>/<slug:object>/', views.done_task,
         name='done_task'),
    path('vk/', views.vk),
    path('lead/', views.LeadList.as_view(), name='crm_lead'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-file/<int:pk>/<slug:object>/', views.add_file, name='add_file'),
    path('customer-filter/', views.customer_list_filter, name='crm_all_customer'),
    path('', views.CustomerList.as_view(), name='crm_customers'),

]

crm/forms.py
from django import forms
from django.contrib.gis.geoip2.resources import Country
from django.core.exceptions import ValidationError

from .models import *
from .validation import validation_ru_letters, validation_phone


class CustomerForm(forms.ModelForm):
    fio_choices = forms.ModelChoiceField(
        queryset=Customer.objects.filter(social_web__id_user__isnull=True),
        widget=forms.Select(attrs={
                                             'class': 'form-control col',
                                             'name': 'first_name'

                                         }), )

    class Meta:
        model = Customer
        fields = '__all__'

    def clean_last_name(self):
        return validation_ru_letters(self.cleaned_data['last_name'])

    def clean_first_name(self):
        return validation_ru_letters(self.cleaned_data['first_name'])

    def clean_family_name(self):
        return validation_ru_letters(self.cleaned_data['family_name'])

    def clean_phone(self):
        return validation_phone(self.cleaned_data['phone'])


class OrderForm(forms.ModelForm):
    """Создание заказа на первой итерации"""
    class Meta:
        model = Order
        fields = ['title']


class CommentForm(forms.ModelForm):
    text = forms.CharField()
    to = forms.ModelChoiceField(User.objects.all(),
                                      empty_label='Кому')

    class Meta:
        model = Comment
        fields = ['text', 'to']


class TaskForm(forms.ModelForm):
    task = forms.CharField()
    to = forms.ModelChoiceField(User.objects.all(), empty_label='Исполнитель')
    type_task = forms.ModelChoiceField(TypeTask.objects.all(), empty_label='Тип задачи')

    class Meta:
        model = Task
        fields = ['task', 'to', 'deadline', 'type_task']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title']


class MeasuringForm(forms.ModelForm):
    class Meta:
        model = Measuring
        fields = ['measuring']


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project']


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ['num_flat', 'num_door', 'num_level', 'num_house', 'num_housing']


class CountryForm(forms.ModelForm):
    class Meta:
        model = AddressCountry
        fields = '__all__'


class AreaForm(forms.ModelForm):
    class Meta:
        model = AddressArea
        fields = '__all__'


class RegionForm(forms.ModelForm):
    class Meta:
        model = AddressRegion
        fields = '__all__'


class TownForm(forms.ModelForm):
    class Meta:
        model = AddressTown
        fields = '__all__'


class StreetForm(forms.ModelForm):
    class Meta:
        model = AddressStreet
        fields = '__all__'

crm/views.py
import json
import os
from datetime import datetime, timedelta
from itertools import chain
from operator import attrgetter

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db.models import Sum, Case, When, Max, Value, Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView

import httplib2
from apiclient import discovery
from oauth2client.service_account import ServiceAccountCredentials
from vk_api import vk_api
from vk_api.utils import get_random_id

from core import settings
from crm.models import Customer, Comment, Task, AddressCountry, AddressArea, \
    AddressRegion, AddressTown, AddressStreet, Address, Order, Product, \
    SocialWebCustomers, SourceCustomer, Measuring, Project, Files, Lead, \
    StatusOrder
from users.forms import UserSettingsStatusCustomerForm
from users.models import AnySettingsUser
from .forms import CustomerForm, CommentForm, TaskForm, OrderForm, AddressForm, \
    CountryForm, AreaForm, RegionForm, TownForm, StreetForm, ProductForm, \
    MeasuringForm, ProjectForm

from .services.services import (
    get_context_comm_window,
    get_customer_orders,
    Vkontakte,
    get_customer_addresses)


from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.utils.decorators import method_decorator


class LoginRequired(View):
    """
    Redirects to login if user is anonymous
    """
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequired, self).dispatch(*args, **kwargs)

group_token = 'vk1.a.QFfRyZ7gjlvH6GcFDvq2jYY9Il2F8K9CzoQNoI3HF3qRCsQRM5Cr08pU2bwTXHbfzFsEGkBwYmPzZ2JU3gszmcZ6BVOQFkH2ZVs_M-z2NVlyEbh1ykGvmOVhz1L8PoCgmbjKo4hQfHmInjIi0V1cIke2KqfudBCId0k7WEcr3djEPZUZiyIipm4y_dHVyPKnM3YW2Z6jlGauYbI56q2B3Q'
ACTIONS = [['Комментарий', 'comment'], ['Задача', 'task'], ['VK', 'VK']]


class CustomerList(LoginRequired, ListView):
    model = Customer
    template_name = 'crm/crm_customers.html'
    paginate_by = 10

    def get_queryset(self):
        unread = {}
        for dialog in Vkontakte().get_group_conversations['items']:
            try:
                if dialog['conversation']['unread_count']:
                    cust = Customer.objects.filter(
                        social_web__id_user=dialog['conversation']['peer'][
                            'id']).values('pk').get()['pk']
                    unread[cust] = \
                        dialog['conversation']['unread_count']
            except:
                continue

        customers = Customer.objects.filter(
            status_customer__in=list(AnySettingsUser.objects.filter(
                user=self.request.user).values(
                'filter_customer_list'))[0]['filter_customer_list'])
        only_active_order = AnySettingsUser.objects.filter(user=self.request.user, customers_with_active_order=True).exists()
        search_query = self.request.GET.get('search', '')
        for c in customers:
            if c.pk in unread:
                c.unread = unread[c.pk]
        if only_active_order:
            return customers.filter(is_active_order=True)
        if search_query:
            return customers.filter(Q(last_name__iregex=search_query))
        return customers

    def get_context_data(self, *args, **kwargs):
        unread = {}
        for dialog in Vkontakte().get_group_conversations['items']:
            try:
                if dialog['conversation']['unread_count']:
                    cust = Customer.objects.filter(
                        social_web__id_user=dialog['conversation']['peer'][
                            'id']).values('pk').get()['pk']
                    unread[cust] = \
                        dialog['conversation']['unread_count']
            except:
                continue
        context = super().get_context_data(*args, **kwargs)
        context['form'] = CustomerForm
        context['unread'] = unread
        comments = Comment.objects.filter(is_show=False, to=self.request.user)
        tasks = Task.objects.filter(is_show=False, to=self.request.user)
        context['notification'] = sorted(chain(comments, tasks), key=attrgetter(
            'date'), reverse=True)[::-1]
        context['status_customer'] = AnySettingsUser.STATUS_CUSTOMER
        context[
            'user_settings_status_customer_form'] = UserSettingsStatusCustomerForm(instance=AnySettingsUser.objects.get(user=self.request.user))
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            if 'first_name' in request.POST:
                form = CustomerForm(request.POST)
                if form.is_valid():
                    customer = form.save(commit=False)
                    customer.creater_customer = request.user
                    customer.save()
                    return redirect('crm:crm_customers')
                return render(request, 'crm/crm_customers.html', {
                    'object_list': Customer.objects.all(),
                    'form': form,
                    'show': 'show',
                })
            if 'filter_customer_list' in request.POST:
                AnySettingsUser.objects.filter(user=request.user).update(
                    filter_customer_list=request.POST.getlist('filter_customer_list'))
                return redirect('crm:crm_customers')


def customer_list_filter(request):
    if AnySettingsUser.objects.filter(user=request.user,
                                      customers_with_active_order=True).exists():
        AnySettingsUser.objects.filter(user=request.user).update(
            customers_with_active_order=False)
    else:
        AnySettingsUser.objects.filter(user=request.user).update(
            customers_with_active_order=True)
    return redirect('crm:crm_customers')


class CustomerDetail(LoginRequired, DetailView):
    model = Customer
    template_name = 'crm/crm_customer_detail.html'

    def get(self, request, *args, **kwargs):
        Customer.objects.filter(pk=self.kwargs['pk'], status_customer=1).update(is_show=True,
                                                             status_customer=2)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        Comment.objects.filter(is_show=False, to=self.request.user,
                               content_type=12,
                               object_id=self.kwargs['pk']).update(
            is_show=True)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer_id = self.kwargs['pk']
        context['new_comment'] = CommentForm
        context['new_task'] = TaskForm
        context['address_list'] = get_customer_addresses(customer_id)
        context['new_order'] = OrderForm
        context['actions'] = ACTIONS
        context['order_list'] = get_customer_orders(customer_id)
        context['select'] = 'comment'
        try:
            context['vk_id'] = SocialWebCustomers.objects.get(
                customer=customer_id,
                name_social=SourceCustomer.objects.get(pk=1))
        except:
            context['vk_id'] = 0
        comments = Comment.objects.filter(is_show=False, to=self.request.user)
        tasks = Task.objects.filter(is_show=False, to=self.request.user)
        context['notification'] = sorted(chain(comments, tasks),
                                         key=attrgetter('date'), reverse=True)[
                                  ::-1]
        context['status_customer'] = AnySettingsUser.STATUS_CUSTOMER
        context.update(get_context_comm_window(Customer, customer_id))
        return context

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            template = 'crm/includes/crm_communication_window.html'
            if 'title' in request.POST:
                form = OrderForm(request.POST)
                customer = self.kwargs.get('pk')
                form_add_order = form.save(commit=False)
                form_add_order.customer = Customer.objects.get(pk=customer)
                form_add_order.status_order = StatusOrder.objects.get(start_status=True)
                Customer.objects.filter(pk=customer).update(is_active_order=True)
                form.save()
                return redirect('crm:crm_customer_detail', pk=customer)
            if 'last_name' in request.POST:
                customer = self.kwargs.get('pk')
                instance = get_object_or_404(Customer, pk=customer)
                form = CustomerForm(request.POST, instance=instance)
                form.save()
                return redirect('crm:crm_customer_detail', pk=customer)
            if 'street_title' in request.POST:
                customer_id = self.kwargs.get('pk')
                customer = get_object_or_404(Customer, pk=customer_id)
                country = AddressCountry.objects.get_or_create(country_title=request.POST['country_title'])[0]
                area = AddressArea.objects.get_or_create(area_title=request.POST['area_title'])[0]
                region = AddressRegion.objects.get_or_create(region_title=request.POST['region_title'])[0]
                town = AddressTown.objects.get_or_create(town_title=request.POST['town_title'])[0]
                street = AddressStreet.objects.get_or_create(street_title=request.POST['street_title'])[0]
                if Address.objects.filter(customer=customer).exists():
                    instance = get_object_or_404(Address, customer=customer)
                    form = AddressForm(request.POST, instance=instance)
                else:
                    form = AddressForm(request.POST)
                address = form.save(commit=False)
                address.country = country

templates/crm/crm_customer_detail.html
{% extends 'layout.html' %}
{% load tz %}
{#{% load user_filters %}#}
{% load widget_tweaks %}
{% load static %}

{% block title %}
  {{ customer }}
{% endblock %}

<!-- Блок левого меню -->
{% block sidebar %}
  {% include 'crm/includes/crm_sidebar.html' %}
{% endblock %}

<!-- Блок навигации -->
{% block navigation %}
  {% include 'crm/includes/crm_navigation.html' %}
{% endblock %}

<!-- Блок контента -->
{% block content %}


<script src="{% static "/pro/assets/js/soft-ui-dashboard.js" %}"></script>
  <style>
      .scrolling-wrapper {
          overflow-x: auto;
      }

      .card-block {
          height: 300px;
          background-color: #fff;
          border: none;
          background-position: center;
          background-size: cover;
          transition: all 0.2s ease-in-out !important;
      }

      .sticky {
          position: sticky;
          top: 0;
          min-height: 2em;
          z-index: 100;
      }
  </style>
  <div class="container-fluid py-4">
    <div class="row tab-content" id="pills-tabContent">
      <div class="col-12 col-md-4 mb-md-0 mb-1">
        <div class="card h-100">
          <div class="card-header pb-0 p-3">
            <div class="row">
              <div class="col-md-7 d-flex align-items-center">
                <h6 class="mb-0">{{ customer }}</h6>
              </div>
              <div class="col-md-5 text-end">
                {% if customer.status_customer == 2 or customer.status_customer == 3 %}
                <a type="button"
                   hx-get="{% url 'crm:crm_customer_edit' customer.pk %}"
                   hx-target="#r">
                  <i class="fas fa-user-edit text-secondary text-sm"
                     data-bs-toggle="tooltip" data-bs-placement="top"
                     title="Изменить профиль"></i>
                </a>
                <a type="button"
                   hx-get="{% url 'crm:crm_address_edit' customer.pk %}"
                   hx-target="#r">
                  <i class="fas fa-address-card text-secondary text-sm mx-3"
                     data-bs-toggle="tooltip" data-bs-placement="top"
                     title="Изменить адрес"></i>
                </a>
                <a type="button"
                   href="{% url 'crm:crm_close_customer' customer.pk %}">
                  <i class="fas fa-times text-secondary text-sm"
                     data-bs-toggle="tooltip" data-bs-placement="top"
                     title="Пометить как неактивный"></i>
                </a>
                {% endif %}
              {% if customer.status_customer == 6 %}
              <a type="button"
                   href="{% url 'crm:crm_close_customer' customer.pk %}">
                  <i class="fas fa-unlock text-secondary text-sm"
                     data-bs-toggle="tooltip" data-bs-placement="top"
                     title="Вернуть активность"></i>
                </a>
              {% endif %}
              </div>
            </div>
          </div>
          <div class="card-body p-3">
            <div id="r">
              {% include 'crm/includes/crm_customer_info_body.html' %}
            </div>
          </div>
        </div>
      </div> <!-- Блок с информацией о клиенте -->
      <div class="col-12 col-md-8 mt-md-0 mt-1">
        <div class="card blur shadow-blur height-600">
          <div class="card-body overflow-auto overflow-x-hidden"
               id="parentDiv">
            {% include 'crm/includes/crm_communication_window.html' %}
          </div>
          <div class="row card-footer  pb-3 pt-3 align-items-center">
            <div class="col-1">
              <button class="  btn btn-icon-only shadow-none text-dark mb-0"
                      type="button" data-bs-toggle="collapse"
                      data-bs-target="#collapseSettingsCommunication"
                      aria-expanded="false"
                      aria-controls="collapseSettingsCommunication">
                <i class="ni ni-settings"></i>
              </button>
            </div>
            <div class="col-auto p-0">
              <div class="col-xl-3 col-md-3 m-0 collapse collapse-horizontal"
                   id="collapseSettingsCommunication">
                <div class="form-group p-0 m-0"
                     style="width: 150px;">
                  <select name="action" class="form-control"
                          hx-get="{% url 'crm:get_form_communication' %}"
                          hx-trigger="change" hx-target="#communication">
                    {% for action, key in actions %}

                      <option value="{{ key }}">{{ action }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
            </div>
            <form class="col row" method="post" id="form-comm">
              {% csrf_token %}
              <div class=" col input-group" id="communication">
                {% include 'crm/includes/crm_form_communication/crm_comment.html' %}
              </div>
              <button id="submit-comm" type="submit"
                      class="col-2 btn bg-gradient-light mb-0 ms-2"
{#                      hx-post="{{ request.get_full_path }}"#}
                      hx-target="#parentDiv"
                      >
                <i class="ni ni-send"></i>
              </button>
            </form>
          </div>
        </div>
      </div><!-- Коммуникационное окно -->
    </div>
    <div class="row">
      <div class="col-12 mt-4">
        <div class="card mb-4">
          <div class="card-header pb-0 p-3">
            <h6 class="mb-1">Заказы</h6>
            <p class="text-sm">Список заказов клиента</p>
          </div>
          <div class="card-body p-3">
            <div class="row scrolling-wrapper d-flex flex-row flex-nowrap  mt-4 pb-4 pt-2">
              <style>
                  .new-order:hover {
                      cursor: pointer;
                  }
              </style>
              <div class="col-xl-3 col-md-3 mb-xl-0 mb-4 new-order">
                <div class="card height-300 card-plain border">
                  <div class="card-body d-flex flex-column justify-content-center text-center"
                       data-bs-toggle="collapse"
                       data-bs-target="#collapseWidthExample"
                       aria-expanded="false"
                       aria-controls="collapseWidthExample">
                    <i class="fa fa-plus text-secondary mb-3"></i>
                    <h5 class=" text-secondary"> Новый заказ </h5>
                  </div>
                </div>
              </div> <!-- Кнопка новый заказ -->
              <div class="col-auto  p-0">
                <div class="col-xl-3 col-md-3 mb-xl-0 mb-4 collapse collapse-horizontal"
                     id="collapseWidthExample">
                  <div class="card height-300 card-plain border"
                       style="width: 250px;">
                    <form class="card-body d-flex flex-column justify-content-center text-center"
                          action="" method="post">
                      {% csrf_token %}
                      {% render_field new_order.title class='form-control mb-3' placeholder='Название заказа' %}
                      <button class="btn btn-secondary" type="submit">
                        Добавить
                      </button>
                    </form>
                  </div>
                </div>
              </div><!-- Форма нового заказа -->
              {% for order in order_list %}
                <div class="col-xl-3 col-md-3 mb-xl-0 mb-4 card-block">
                  <div class="card card-blog card-plain">
                    <div class="position-relative d-none d-md-block">
                      <a class="d-block shadow-xl border-radius-xl">
                        <img src="{% static 'img/standart_order_img.jpeg' %}"
                             alt="img-blur-shadow"
                             class="img-fluid shadow border-radius-xl">
                      </a>
                    </div>
                    <div class="card-body px-1 pb-0">
                      <a href="{% url 'crm:crm_order_detail' order.pk %}">
                        <h5>
                          {{ order.title }}
                        </h5>
                      </a>
                      <p class="mb-4 text-sm">
                        Стоимость: {{ order.price }}
                      </p>
                      <p class="mb-4 text-sm">
                        Дата создания: {{ order.date }}
                      </p>
                      <div class="d-flex align-items-center justify-content-between">
                      </div>
                    </div>
                  </div>
                </div> <!-- Карточка заказа -->
              {% endfor %}
            </div>
          </div>
        </div>
      </div> <!-- Блок заказов -->
    </div>
  </div>

  <div class="modal fade" id="done_task_window" tabindex="-1" role="dialog"
       aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Выполнить задачу</h5>
          <button type="button" class="btn-close text-dark"
                  data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="post">
          {% csrf_token %}
          <div class="modal-body">
            <p class="name-task"> Завершить задачу:</p>
            <p id="name-task-modal"></p>
            <input id="modal_body" name="done_task" type="hidden">
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn bg-gradient-dark">Завершить
            </button>
            <button type="button" class="btn bg-gradient-light"
                    data-bs-dismiss="modal">Отмена
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>


  <!-- Import jquery cdn -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
          integrity=
                  "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
          crossorigin="anonymous">
  </script>

  <script>
      var objDiv = document.getElementById("parentDiv");
      objDiv.scrollTop = objDiv.scrollHeight;
      $("#submit-comm").click(function () {
          setTimeout(() => {
              document.getElementById("form-comm").reset();
          }, 100);
      })
  </script>

{% endblock %}

templates/crm/crm_customers.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
  Клиенты
{% endblock %}

<!-- Блок левого меню -->
{% block sidebar %}
  {% include 'crm/includes/crm_sidebar.html' %}
{% endblock %}

<!-- Блок навигации -->
{% block navigation %}
  {% include 'crm/includes/crm_navigation.html' %}
{% endblock %}

<!-- Блок контента -->
{% block content %}

  <style>
      tr.customer:hover {
          cursor: pointer;
      }
  </style>
  <div class="container-fluid py-4">

    <div class="d-sm-flex justify-content-between">
      <div>
        <a href="javascript:;" class="btn btn-icon bg-gradient-dark"
           data-bs-toggle="collapse"
           data-bs-target="#collapseFormCustomer"
           aria-expanded="false" aria-controls="collapseFormCustomer">
          Новый клиент
        </a>
      </div>
      <div class="d-flex">
        <a href="{% url 'crm:crm_all_customer' %}" class="btn {% if request.user.settings.customers_with_active_order == False %} btn-light{% else %} btn-success {% endif %}">Только клиенты с заказами</a>
        <div class="dropdown d-inline ms-2">
          <a href="javascript:;" class="btn btn-outline-dark dropdown-toggle "
             data-bs-toggle="dropdown" id="navbarDropdownMenuLink2">
            Фильтр
          </a>

          <form method="post" action="{% url 'crm:crm_customers' %}" class="dropdown-menu dropdown-menu-lg-start px-2 py-3"
{#                aria-labelledby="navbarDropdownMenuLink2"#}
{#                data-popper-placement="left-start"#}
{#                hx-get="{% url 'crm:customer-filter' %}" hx-trigger="change"#}
{#                hx-target="#customer-list"#}
          >
{% csrf_token %}
            {{ user_settings_status_customer_form.as_p }}
            <div>
              <hr class="horizontal dark my-2">
            </div>
            <div>
              <button type="submit" class="dropdown-item border-radius-md text-success"
              >Выбрать
              </button>
            </div>
          </form>


        </div>
        <button class="btn btn-icon btn-outline-dark ms-2 export"
                data-type="csv"
                type="button">
          <span class="btn-inner--icon"><i class="ni ni-archive-2"></i></span>
          <span class="btn-inner--text">Экспорт</span>
        </button>
      </div>
    </div>

    <div class="row" id="customer-list">
      {% include 'crm/includes/customer_list.html' %}
    </div>
  <div class="d-flex justify-content-center">
  <div class="pagination-container justify-content-center">
    <ul class="pagination pagination-secondary">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="Previous">
            <span aria-hidden="true"><i class="fa fa-angle-double-left"
                                        aria-hidden="true"></i></span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
             aria-label="Previous">
          <span aria-hidden="true"><i class="fa fa-angle-left"
                                      aria-hidden="true"></i></span>
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <a class="page-link text-light" href="javascript:;">{{ i }}</a>
          </li>
        {% elif i >= page_obj.number|add:-2 and i <= page_obj.number|add:2  %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}"
             aria-label="Next">
          <span aria-hidden="true"><i class="fa fa-angle-right"
                                      aria-hidden="true"></i></span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"
             aria-label="Next">
      <span aria-hidden="true"><i class="fa fa-angle-double-right"
                                  aria-hidden="true"></i></span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
  </div>
  </div>

  <script>
      let url = `ws://0.0.0.0:8001/ws/new_customer/`

      const chatSocket = new WebSocket(url)

      chatSocket.onmessage = function (e) {
          let data = JSON.parse(e.data)
          console.log('Data:', data)

          if (data.type === 'new_customer') {
              let messages = document.getElementById('customers_list')

              messages.insertAdjacentHTML('afterbegin', `
 <tr class="customer">
                    <td onclick="document.location = '/crm/customer/${data.status}'">
                      <div class="d-flex px-2 py-1">
                        <div class="d-flex flex-column justify-content-center">
                          <h6 class="mb-0 text-sm">${data.cust}</h6>
{#                          <p class="text-xs text-secondary mb-0">john@creative-tim.com</p>#}
                        </div>
                      </div>
                    </td>
                    <td>
                      <p class="text-xs font-weight-bold mb-0"></p>
{#                      <p class="text-xs text-secondary mb-0">Organization</p>#}
                    </td>
                    <td class="align-middle text-center text-sm">


                          <span class="badge badge-sm bg-gradient-info">
                          Неразобран
                          </span>


                    </td>
                    <td class="align-middle text-center">
                      <span class="text-secondary text-xs font-weight-bold">${data.source}</span>
                    </td>

                  </tr>
`)
          }
      }
  </script>





{% endblock %}