core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('user/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
]

crm/urls.py
from django.urls import path

from crm import views

app_name = 'crm'

urlpatterns = [
    path('customer/form_communication/', views.get_form_communication,
         name='get_form_communication'),
    path('customer/<int:pk>/close_customer/', views.close_customer,
         name='crm_close_customer'),
    path('customer/<int:pk>/', views.CustomerDetail.as_view(),
         name='crm_customer_detail'),
    path('customer/<int:pk>/edit/', views.customer_edit,
         name='crm_customer_edit'),
    path('customer/<int:pk>/address/edit/', views.address_edit,
         name='crm_address_edit'),
    # path('customer-filter/', views.customer_list_filter, name='customer-filter'),
    path('order/<int:pk>/', views.OrderDetail.as_view(),
         name='crm_order_detail'),
    path('orders/product/<int:pk>/', views.ProductDetail.as_view(), name='crm_product_detail'),
    path('tasks/start/<int:pk>/<int:cust_pk>/<slug:object>/', views.start_task,
         name='start_task'),
    path('tasks/done/<int:cust_pk>/<int:pk>/<slug:object>/', views.done_task,
         name='done_task'),
    path('vk/', views.vk),
    path('lead/', views.LeadList.as_view(), name='crm_lead'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-file/<int:pk>/<slug:object>/', views.add_file, name='add_file'),
    path('customer-filter/', views.customer_list_filter, name='crm_all_customer'),
    path('', views.CustomerList.as_view(), name='crm_customers'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetCompleteView, PasswordResetConfirmView,
    PasswordResetDoneView, PasswordResetView, PasswordChangeDoneView,
    PasswordChangeView)

from . import views
from .views import LoginUserCustom

app_name = 'users'

urlpatterns = [
    path('profile/<int:pk>/',
         views.ProfileUser.as_view(),
         name='profile'),
    path('logout/',
         LogoutView.as_view(),
         name='logout'),
    # path('signup/',
    #      views.SignUp.as_view(),
    #      name='signup'),
    path('login/',
         LoginUserCustom.as_view(
             template_name='users/login.html'),
         name='login'),
    # path('password_change/',
    #      PasswordChangeView.as_view(
    #          template_name='users/password_change_form.html'),
    #      name='password_change'),
    # path('password_change/done/',
    #      PasswordChangeDoneView.as_view(
    #          template_name='users/password_change_done.html'),
    #      name='password_change_done'),
    # path('password_reset/',
    #      PasswordResetView.as_view(
    #          template_name='users/password_reset_form.html'),
    #      name='password_reset'),
    # path('password_reset/done/',
    #      PasswordResetDoneView.as_view(
    #          template_name='users/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      PasswordResetCompleteView.as_view(
    #          template_name='users/password_reset_complete.html'),
    #      name='password_reset_complete'),
]

users/models.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models

User = get_user_model()


def get_first_name(self):
    return f'{self.first_name} {self.last_name}'


User.add_to_class("__str__", get_first_name)


STATUS_CUSTOMER = ((1, 'Неразобран'),
                   (2, 'Новый'),
                   (3, 'Нет активных задач'),
                   (4, 'Есть активные задачи'),
                   (5, 'Действующий'),
                   (6, 'Неактивный'),)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='user')
    status_staff = models.ForeignKey(
        'StatusStaff',
        verbose_name='должность',
        on_delete=models.PROTECT,
        related_name='profile',
        blank=True,
        null=True
    )

    def __str__(self):
        return str(self.user)

    class Meta:
        managed = False


class StatusStaff(models.Model):
    status_staff = models.CharField(verbose_name='должность', max_length=20)

    def __str__(self):
        return self.status_staff

    class Meta:
        managed = False


class ModifiedArrayField(ArrayField):
    def formfield(self, **kwargs):
        defaults = {
            "form_class": forms.MultipleChoiceField,
            "choices": self.base_field.choices,
            "widget": forms.CheckboxSelectMultiple,
            **kwargs
        }
        return super(ArrayField, self).formfield(**defaults)

    class Meta:
        managed = False


class AnySettingsUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='settings')
    STATUS_CUSTOMER = ((1, 'Неразобран'),
                       (2, 'Новый'),
                       (3, 'Нет активных задач'),
                       (4, 'Есть активные задачи'),
                       (5, 'Действующий'),
                       (6, 'Неактивный'),)

    filter_customer_list = ModifiedArrayField(
        models.CharField(
            choices=STATUS_CUSTOMER,
            max_length=100,
            blank=True,
            null=True
        ),
        blank=True,
        null=True
    )
    customers_with_active_order = models.BooleanField(default=False)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from users.models import AnySettingsUser

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class UserSettingsStatusCustomerForm(forms.ModelForm):
    class Meta:
        model = AnySettingsUser
        fields = ['filter_customer_list']

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView

from .models import Profile, AnySettingsUser


class LoginRequired(View):
    """
    Redirects to login if user is anonymous
    """
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequired, self).dispatch(*args, **kwargs)


class LoginUserCustom(LoginView):
    def get_success_url(self):
        if not Profile.objects.filter(user=self.request.user).exists():
            Profile.objects.create(user=self.request.user)
        if not AnySettingsUser.objects.filter(user=self.request.user).exists():
            AnySettingsUser.objects.create(user=self.request.user,
                                           filter_customer_list=[1, 2, 3, 4, 5,
                                                                 6])
        return super().get_success_url()


class ProfileUser(LoginRequired, DetailView):
    template_name = 'users/profile.html'
    model = Profile
    context_object_name = 'profile'

templates/users/login.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
  Клиенты
{% endblock %}

<!-- Блок левого меню -->
{% block sidebar %}
  {% include 'crm/includes/crm_sidebar.html' %}
{% endblock %}

<!-- Блок навигации -->
{% block navigation %}
  {% include 'crm/includes/crm_navigation.html' %}
{% endblock %}

<!-- Блок контента -->
{% block content %}
  <main class="main-content  mt-0">
    <section>
      <div class="page-header min-vh-75">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-6 d-flex flex-column mx-auto">
              <div class="card card-plain mt-8">
                <div class="card-header pb-0 text-left bg-transparent">
                  <h3 class="font-weight-bolder text-info text-gradient">Вход</h3>
                  <p class="mb-0">Введите логин и пароль</p>
                </div>
                <div class="card-body">
                  <form role="form" action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    <label>Логин</label>
                    <div class="mb-3">
                      {% render_field form.username class="form-control" placeholder="Логин" aria-label="Email" aria-describedby="email-addon" %}
                    </div>
                    <label>Пароль</label>
                    <div class="mb-3">
                      {% render_field form.password type="password" class="form-control" placeholder="Пароль" aria-label="Email" aria-describedby="email-addon" %}
                    </div>
                    <div class="form-check form-switch">
                      <input class="form-check-input" type="checkbox" id="rememberMe" checked="">
                      <label class="form-check-label" for="rememberMe">Запомни меня</label>
                    </div>
                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Войти</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="oblique position-absolute top-0 h-100 d-md-block d-none me-n8">
                <div class="oblique-image bg-cover position-absolute fixed-top ms-auto h-100 z-index-0 ms-n6" style="background-image:url({% static "/img/curved-images/bg-login.jpeg" %})">123</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>

  <style>
  tr.customer:hover{
      cursor: pointer;
  }
  </style>


  <!-- Окно создания выплывающее слева -->
{#  {% include 'crm/includes/crm_modal_form.html' with title='Новый клиент' %}#}



{% endblock %}

templates/users/profile.html
{% extends 'layout.html' %}
{% load tz %}
{#{% load user_filters %}#}
{% load widget_tweaks %}
{% load static %}

{% block title %}
  {{ customer }}
{% endblock %}

<!-- Блок левого меню -->
{% block sidebar %}
  {% include 'crm/includes/crm_sidebar.html' %}
{% endblock %}

<!-- Блок навигации -->
{% block navigation %}
  {% include 'crm/includes/crm_navigation.html' %}
{% endblock %}

<!-- Блок контента -->
{% block content %}


<div class="container-fluid">
  <div class="page-header min-height-100 border-radius-xl mt-4">
  </div>
  <div class="card card-body blur shadow-blur mx-4 mt-n6 overflow-hidden">
    <div class="row gx-4">
      <div class="col-auto my-auto">
        <div class="h-100">
          <h5 class="mb-1">
            {{ profile.user }}
          </h5>
          <p class="mb-0 font-weight-bold text-sm">
            {{ profile.status_staff }}
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid py-4">
  <div class="row mt-3">
  </div>
</div>


{% endblock %}

templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<form action="{% url 'users:signup' %}">
  {% csrf_token %}
{{ form }}

  </form>
</body>
</html>
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Signin Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">



    <!-- Bootstrap core CSS -->

    <link href={% static 'assets/dist/css/bootstrap.min.css' %} rel="stylesheet">

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href={% static 'css/signin.css' %} rel="stylesheet">
  </head>
  <body class="text-center">

<main class="form-signin">
  <form>
    <img class="mb-4" src="{% static 'img/bootstrap-logo.svg' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>



  </body>
</html>