core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('user/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
]

crm/urls.py
from django.urls import path

from crm import views

app_name = 'crm'

urlpatterns = [
    path('customer/form_communication/', views.get_form_communication,
         name='get_form_communication'),
    path('customer/<int:pk>/close_customer/', views.close_customer,
         name='crm_close_customer'),
    path('customer/<int:pk>/', views.CustomerDetail.as_view(),
         name='crm_customer_detail'),
    path('customer/<int:pk>/edit/', views.customer_edit,
         name='crm_customer_edit'),
    path('customer/<int:pk>/address/edit/', views.address_edit,
         name='crm_address_edit'),
    # path('customer-filter/', views.customer_list_filter, name='customer-filter'),
    path('order/<int:pk>/', views.OrderDetail.as_view(),
         name='crm_order_detail'),
    path('orders/product/<int:pk>/', views.ProductDetail.as_view(), name='crm_product_detail'),
    path('tasks/start/<int:pk>/<int:cust_pk>/<slug:object>/', views.start_task,
         name='start_task'),
    path('tasks/done/<int:cust_pk>/<int:pk>/<slug:object>/', views.done_task,
         name='done_task'),
    path('vk/', views.vk),
    path('lead/', views.LeadList.as_view(), name='crm_lead'),
    path('search/', views.Search.as_view(), name='search'),
    path('add-file/<int:pk>/<slug:object>/', views.add_file, name='add_file'),
    path('customer-filter/', views.customer_list_filter, name='crm_all_customer'),
    path('', views.CustomerList.as_view(), name='crm_customers'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetCompleteView, PasswordResetConfirmView,
    PasswordResetDoneView, PasswordResetView, PasswordChangeDoneView,
    PasswordChangeView)

from . import views
from .views import LoginUserCustom

app_name = 'users'

urlpatterns = [
    path('profile/<int:pk>/',
         views.ProfileUser.as_view(),
         name='profile'),
    path('logout/',
         LogoutView.as_view(),
         name='logout'),
    # path('signup/',
    #      views.SignUp.as_view(),
    #      name='signup'),
    path('login/',
         LoginUserCustom.as_view(
             template_name='users/login.html'),
         name='login'),
    # path('password_change/',
    #      PasswordChangeView.as_view(
    #          template_name='users/password_change_form.html'),
    #      name='password_change'),
    # path('password_change/done/',
    #      PasswordChangeDoneView.as_view(
    #          template_name='users/password_change_done.html'),
    #      name='password_change_done'),
    # path('password_reset/',
    #      PasswordResetView.as_view(
    #          template_name='users/password_reset_form.html'),
    #      name='password_reset'),
    # path('password_reset/done/',
    #      PasswordResetDoneView.as_view(
    #          template_name='users/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/done/',
    #      PasswordResetCompleteView.as_view(
    #          template_name='users/password_reset_complete.html'),
    #      name='password_reset_complete'),
]

crm/forms.py
from django import forms
from django.contrib.gis.geoip2.resources import Country
from django.core.exceptions import ValidationError

from .models import *
from .validation import validation_ru_letters, validation_phone


class CustomerForm(forms.ModelForm):
    fio_choices = forms.ModelChoiceField(
        queryset=Customer.objects.filter(social_web__id_user__isnull=True),
        widget=forms.Select(attrs={
                                             'class': 'form-control col',
                                             'name': 'first_name'

                                         }), )

    class Meta:
        model = Customer
        fields = '__all__'

    def clean_last_name(self):
        return validation_ru_letters(self.cleaned_data['last_name'])

    def clean_first_name(self):
        return validation_ru_letters(self.cleaned_data['first_name'])

    def clean_family_name(self):
        return validation_ru_letters(self.cleaned_data['family_name'])

    def clean_phone(self):
        return validation_phone(self.cleaned_data['phone'])


class OrderForm(forms.ModelForm):
    """Создание заказа на первой итерации"""
    class Meta:
        model = Order
        fields = ['title']


class CommentForm(forms.ModelForm):
    text = forms.CharField()
    to = forms.ModelChoiceField(User.objects.all(),
                                      empty_label='Кому')

    class Meta:
        model = Comment
        fields = ['text', 'to']


class TaskForm(forms.ModelForm):
    task = forms.CharField()
    to = forms.ModelChoiceField(User.objects.all(), empty_label='Исполнитель')
    type_task = forms.ModelChoiceField(TypeTask.objects.all(), empty_label='Тип задачи')

    class Meta:
        model = Task
        fields = ['task', 'to', 'deadline', 'type_task']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title']


class MeasuringForm(forms.ModelForm):
    class Meta:
        model = Measuring
        fields = ['measuring']


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project']


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ['num_flat', 'num_door', 'num_level', 'num_house', 'num_housing']


class CountryForm(forms.ModelForm):
    class Meta:
        model = AddressCountry
        fields = '__all__'


class AreaForm(forms.ModelForm):
    class Meta:
        model = AddressArea
        fields = '__all__'


class RegionForm(forms.ModelForm):
    class Meta:
        model = AddressRegion
        fields = '__all__'


class TownForm(forms.ModelForm):
    class Meta:
        model = AddressTown
        fields = '__all__'


class StreetForm(forms.ModelForm):
    class Meta:
        model = AddressStreet
        fields = '__all__'

crm/views.py
import json
import os
from datetime import datetime, timedelta
from itertools import chain
from operator import attrgetter

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db.models import Sum, Case, When, Max, Value, Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView

import httplib2
from apiclient import discovery
from oauth2client.service_account import ServiceAccountCredentials
from vk_api import vk_api
from vk_api.utils import get_random_id

from core import settings
from crm.models import Customer, Comment, Task, AddressCountry, AddressArea, \
    AddressRegion, AddressTown, AddressStreet, Address, Order, Product, \
    SocialWebCustomers, SourceCustomer, Measuring, Project, Files, Lead, \
    StatusOrder
from users.forms import UserSettingsStatusCustomerForm
from users.models import AnySettingsUser
from .forms import CustomerForm, CommentForm, TaskForm, OrderForm, AddressForm, \
    CountryForm, AreaForm, RegionForm, TownForm, StreetForm, ProductForm, \
    MeasuringForm, ProjectForm

from .services.services import (
    get_context_comm_window,
    get_customer_orders,
    Vkontakte,
    get_customer_addresses)


from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.utils.decorators import method_decorator


class LoginRequired(View):
    """
    Redirects to login if user is anonymous
    """
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequired, self).dispatch(*args, **kwargs)

group_token = 'vk1.a.QFfRyZ7gjlvH6GcFDvq2jYY9Il2F8K9CzoQNoI3HF3qRCsQRM5Cr08pU2bwTXHbfzFsEGkBwYmPzZ2JU3gszmcZ6BVOQFkH2ZVs_M-z2NVlyEbh1ykGvmOVhz1L8PoCgmbjKo4hQfHmInjIi0V1cIke2KqfudBCId0k7WEcr3djEPZUZiyIipm4y_dHVyPKnM3YW2Z6jlGauYbI56q2B3Q'
ACTIONS = [['Комментарий', 'comment'], ['Задача', 'task'], ['VK', 'VK']]


class CustomerList(LoginRequired, ListView):
    model = Customer
    template_name = 'crm/crm_customers.html'
    paginate_by = 10

    def get_queryset(self):
        unread = {}
        for dialog in Vkontakte().get_group_conversations['items']:
            try:
                if dialog['conversation']['unread_count']:
                    cust = Customer.objects.filter(
                        social_web__id_user=dialog['conversation']['peer'][
                            'id']).values('pk').get()['pk']
                    unread[cust] = \
                        dialog['conversation']['unread_count']
            except:
                continue

        customers = Customer.objects.filter(
            status_customer__in=list(AnySettingsUser.objects.filter(
                user=self.request.user).values(
                'filter_customer_list'))[0]['filter_customer_list'])
        only_active_order = AnySettingsUser.objects.filter(user=self.request.user, customers_with_active_order=True).exists()
        search_query = self.request.GET.get('search', '')
        for c in customers:
            if c.pk in unread:
                c.unread = unread[c.pk]
        if only_active_order:
            return customers.filter(is_active_order=True)
        if search_query:
            return customers.filter(Q(last_name__iregex=search_query))
        return customers

    def get_context_data(self, *args, **kwargs):
        unread = {}
        for dialog in Vkontakte().get_group_conversations['items']:
            try:
                if dialog['conversation']['unread_count']:
                    cust = Customer.objects.filter(
                        social_web__id_user=dialog['conversation']['peer'][
                            'id']).values('pk').get()['pk']
                    unread[cust] = \
                        dialog['conversation']['unread_count']
            except:
                continue
        context = super().get_context_data(*args, **kwargs)
        context['form'] = CustomerForm
        context['unread'] = unread
        comments = Comment.objects.filter(is_show=False, to=self.request.user)
        tasks = Task.objects.filter(is_show=False, to=self.request.user)
        context['notification'] = sorted(chain(comments, tasks), key=attrgetter(
            'date'), reverse=True)[::-1]
        context['status_customer'] = AnySettingsUser.STATUS_CUSTOMER
        context[
            'user_settings_status_customer_form'] = UserSettingsStatusCustomerForm(instance=AnySettingsUser.objects.get(user=self.request.user))
        return context

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            if 'first_name' in request.POST:
                form = CustomerForm(request.POST)
                if form.is_valid():
                    customer = form.save(commit=False)
                    customer.creater_customer = request.user
                    customer.save()
                    return redirect('crm:crm_customers')
                return render(request, 'crm/crm_customers.html', {
                    'object_list': Customer.objects.all(),
                    'form': form,
                    'show': 'show',
                })
            if 'filter_customer_list' in request.POST:
                AnySettingsUser.objects.filter(user=request.user).update(
                    filter_customer_list=request.POST.getlist('filter_customer_list'))
                return redirect('crm:crm_customers')


def customer_list_filter(request):
    if AnySettingsUser.objects.filter(user=request.user,
                                      customers_with_active_order=True).exists():
        AnySettingsUser.objects.filter(user=request.user).update(
            customers_with_active_order=False)
    else:
        AnySettingsUser.objects.filter(user=request.user).update(
            customers_with_active_order=True)
    return redirect('crm:crm_customers')


class CustomerDetail(LoginRequired, DetailView):
    model = Customer
    template_name = 'crm/crm_customer_detail.html'

    def get(self, request, *args, **kwargs):
        Customer.objects.filter(pk=self.kwargs['pk'], status_customer=1).update(is_show=True,
                                                             status_customer=2)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        Comment.objects.filter(is_show=False, to=self.request.user,
                               content_type=12,
                               object_id=self.kwargs['pk']).update(
            is_show=True)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer_id = self.kwargs['pk']
        context['new_comment'] = CommentForm
        context['new_task'] = TaskForm
        context['address_list'] = get_customer_addresses(customer_id)
        context['new_order'] = OrderForm
        context['actions'] = ACTIONS
        context['order_list'] = get_customer_orders(customer_id)
        context['select'] = 'comment'
        try:
            context['vk_id'] = SocialWebCustomers.objects.get(
                customer=customer_id,
                name_social=SourceCustomer.objects.get(pk=1))
        except:
            context['vk_id'] = 0
        comments = Comment.objects.filter(is_show=False, to=self.request.user)
        tasks = Task.objects.filter(is_show=False, to=self.request.user)
        context['notification'] = sorted(chain(comments, tasks),
                                         key=attrgetter('date'), reverse=True)[
                                  ::-1]
        context['status_customer'] = AnySettingsUser.STATUS_CUSTOMER
        context.update(get_context_comm_window(Customer, customer_id))
        return context

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            template = 'crm/includes/crm_communication_window.html'
            if 'title' in request.POST:
                form = OrderForm(request.POST)
                customer = self.kwargs.get('pk')
                form_add_order = form.save(commit=False)
                form_add_order.customer = Customer.objects.get(pk=customer)
                form_add_order.status_order = StatusOrder.objects.get(start_status=True)
                Customer.objects.filter(pk=customer).update(is_active_order=True)
                form.save()
                return redirect('crm:crm_customer_detail', pk=customer)
            if 'last_name' in request.POST:
                customer = self.kwargs.get('pk')
                instance = get_object_or_404(Customer, pk=customer)
                form = CustomerForm(request.POST, instance=instance)
                form.save()
                return redirect('crm:crm_customer_detail', pk=customer)
            if 'street_title' in request.POST:
                customer_id = self.kwargs.get('pk')
                customer = get_object_or_404(Customer, pk=customer_id)
                country = AddressCountry.objects.get_or_create(country_title=request.POST['country_title'])[0]
                area = AddressArea.objects.get_or_create(area_title=request.POST['area_title'])[0]
                region = AddressRegion.objects.get_or_create(region_title=request.POST['region_title'])[0]
                town = AddressTown.objects.get_or_create(town_title=request.POST['town_title'])[0]
                street = AddressStreet.objects.get_or_create(street_title=request.POST['street_title'])[0]
                if Address.objects.filter(customer=customer).exists():
                    instance = get_object_or_404(Address, customer=customer)
                    form = AddressForm(request.POST, instance=instance)
                else:
                    form = AddressForm(request.POST)
                address = form.save(commit=False)
                address.country = country

templates/crm/includes/crm_communication_window.html
{% load static %}
<!-- Import jquery cdn -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity=
                "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous">
</script>
<script src="{% static "/pro/assets/js/soft-ui-dashboard.js" %}"></script>
{% for date in dates_context %}
  <div class="row mt-2 sticky blur shadow-blur border-radius-xl">
    <div class="col-md-12 text-center">
      <span class="badge text-dark">{{ date }}</span>
    </div>
  </div>
  {% for content in context %}
    {% if date == content.date.date %}
      {% if content.get_my_model_name == 'Message' %}
        {% if content.out == 0 %}
          <div class="row justify-content-start mb-2 mt-1">
            <div class="col-auto">
              <div class="card ">
                <div class="card-body py-2 px-3">
                  <p class="mb-1 text-xs">
                    {{ content.text }}
                  </p>
                  <div class="d-flex align-items-center text-sm opacity-6">
                    <i class="ni ni-check-bold text-sm me-1"></i>
                    <small>{{ content.date }}</small>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- Сообщение входящее -->
        {% else %}
          <div class="row justify-content-end text-right mb-2 mt-1">
            <div class="col-auto">
              <div class="card bg-gray-200">
                <div class="card-body py-2 px-3">
                  <p class="mb-1 text-xs">
                    {{ content.text }}
                  </p>
                  <div class="d-flex align-items-center justify-content-end text-sm opacity-6">
                    <i class="ni ni-check-bold text-sm me-1"></i>
                    <small>{{ content.date }}</small>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- Сообщение исходящее -->
        {% endif %}
      {% elif content.get_my_model_name == 'task' %}
        <div class="d-flex mb-2 mt-1 card flex-row w-100 bg-dark ">
          <div>
            <div class="icon icon-shape bg-danger-soft shadow text-center border-radius-md shadow-none">
              <i class="ni ni-money-coins text-lg text-danger text-gradient opacity-10"
                 aria-hidden="true"></i>
            </div>
          </div>
          <div class="ms-3 ">
            <div class="numbers">
              <h6 class="mb-1 text-white text-sm">{{ content.task }}</h6>
              <span class="text-white-50 text-sm">{{ content.date }}</span>
            </div>

          </div>
          {% if content.is_done %}
            <i class="ni ni-check-bold text-success text-gradient align-self-center ms-auto p-2 bd-highlight"></i>
            {% elif not content.is_show %}
            {% if content.to == request.user %}
            <div class="form-check align-self-center ms-auto p-2 bd-highlight">
              <button hx-get="{% url 'crm:start_task' content.pk object.pk object.get_my_model_name %}"
                      hx-target="#parentDiv"
                      class="btn btn-light text-xxs m-0 p-2"
                      onclick="soft.showSwal('notification', {{ object.pk }}, {{ content.pk }}, '{{ object.get_my_model_name }}')"
                      >В работу
              </button>
            </div>
              {% else %}
              <i class="fa fa-close text-warning text-gradient align-self-center ms-auto p-2 bd-highlight"></i>
              {% endif %}
          {% else %}
            {% if content.to == request.user %}
            <div class="form-check align-self-center ms-auto p-2 bd-highlight">
              <button class="btn btn-danger text-xxs m-0 p-2"
                      onclick="soft.showSwal('warning-message-and-cancel', {{ object.pk }}, {{ content.pk }}, '{{ object.get_my_model_name }}')">
                Завершить
              </button>
            </div>
            {% else %}
              <i class="fa fa-close text-success text-gradient align-self-center ms-auto p-2 bd-highlight"></i>
              {% endif %}
          {% endif %}

        </div> <!-- Задача -->
      {% elif content.get_my_model_name == 'comment' %}
        {% if request.user == content.staff %}
          <div class="row justify-content-end text-right pb-2 pt-1 {% if content.is_show == False and content.to == request.user %} bg-gray-300 {% endif %}">
            <div class="col-auto">
              <div class="card bg-gradient-faded-warning-vertical">
                <div class="card-body py-2 px-3">
                  <p class="mb-1 text-sm">
                    {{ content.text }}
                  </p>
                  <div class="d-flex align-items-center justify-content-end text-sm opacity-6">
                    <i class="ni ni-check-bold text-sm me-1"></i>
                    <small>{{ content.staff }} {{ content.date }}</small>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- Комментарий мой -->
        {% endif %}
        {% if request.user != content.staff %}
          <div class="row justify-content-start pb-2 pt-1 {% if content.is_show == False and content.to == request.user %} bg-gray-300 {% endif %}">
            <div class="col-auto">
              <div class="card bg-gradient-faded-dark">
                <div class="card-body py-2 px-3">
                  <p class="mb-1 text-sm text-white">
                    {{ content.text }}
                  </p>
                  <div class="d-flex align-items-center text-sm opacity-6">
                    <i class="ni ni-check-bold text-sm text-white me-1"></i>
                    <small class="text-white">{{ content.staff }} {{ content.date }}</small>
                  </div>
                </div>
              </div>
            </div>
          </div> <!-- Комментарий не мой -->
        {% endif %}
      {% elif content.get_my_model_name == 'customer' %}
        <div class="d-flex card flex-row mb-2 mt-1 bg-gradient-success">
          <div class="flex-grow-1 ms-3">
            <h6 class="h5 mt-0">Создан клиент</h6>
            <p class="text-sm">{{ content.date }}</p>
          </div>
        </div> <!-- Создан клиент -->
      {% elif content.get_my_model_name == 'order' %}
        <div class="d-flex card flex-row mb-2 mt-1 bg-warning">
          <div class="flex-grow-1 ms-3">
            <h6 class="h5 mt-0">Новый заказ</h6>
            <p class="text-sm">{{ content.title }}</p>
          </div>
        </div> <!-- Создан заказ -->
      {% endif %}
    {% endif %}
  {% endfor %}
{% endfor %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity=
                "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous">
</script>
<script>
    var objDiv = document.getElementById("parentDiv");
    objDiv.scrollTop = objDiv.scrollHeight;
    $("#submit-comm").click(function () {
        setTimeout(() => {
            document.getElementById("form-comm").reset();
        }, 10);
    })
</script>

<script type="text/javascript">
    let url = `ws://0.0.0.0:8000/ws/socket-server/`

    const chatSocket = new WebSocket(url)

    chatSocket.onmessage = function (e) {
        let data = JSON.parse(e.data)
        console.log('Data:', data)

        if (data.type === 'chat') {
            let messages = document.getElementById('parentDiv')

            messages.insertAdjacentHTML('beforeend', `
<div class="row justify-content-start mb-2 mt-1">
            <div class="col-auto">
              <div class="card ">
                <div class="card-body py-2 px-3">
                  <p class="mb-1 text-xs">
                    ${data.message} ${data.text}
                  </p>
                  <div class="d-flex align-items-center text-sm opacity-6">
                    <i class="ni ni-check-bold text-sm me-1"></i>
                    <small>${data.date}</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
`)
            var objDiv = document.getElementById("parentDiv");
    objDiv.scrollTop = objDiv.scrollHeight;
        }
    }

    let form = document.getElementById('form')
    form.addEventListener('submit', (e) => {
        e.preventDefault()
        let message = e.target.message.value
        chatSocket.send(JSON.stringify({
            'message': message
        }))
        form.reset()
    })

</script>

templates/crm/includes/crm_navigation.html
{% load user_filters %}
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl"
       id="navbarBlur" navbar-scroll="true">
    <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
        {% include 'crm/includes/breadcrumbs.html' %}
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4"
           id="navbar">
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
          <form action="{% url 'crm:search' %}">
          <div class="input-group">

          <span class="input-group-text text-body"><i class="fas fa-search"
                                                      aria-hidden="true"></i></span>

              <input type="text" class="form-control" name="search"
                     placeholder="Поиск в базе">

          </div>
          </form>
        </div>
        <ul class="navbar-nav  justify-content-end">

{#          <li class="nav-item d-flex align-items-center">#}
{#            {% if request.user.is_authenticated %}#}
{#              <a href="{% url 'users:logout' %}"#}
{#                 class="nav-link text-body font-weight-bold px-0">#}
{#                <i class="fa fa-user me-sm-1"></i>#}
{#                <span class="d-sm-inline d-none">Выйти</span>#}
{#              </a>#}
{#            {% endif %}#}
{#          </li>#}
          <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
            <a href="javascript:;" class="nav-link text-body p-0"
               id="iconNavbarSidenav">
              <div class="sidenav-toggler-inner">
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
                <i class="sidenav-toggler-line"></i>
              </div>
            </a>
          </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item px-3 d-flex align-items-center">
            <a href="{% url 'users:profile' request.user.user.pk %}" class="nav-link text-body p-0">
              <i class="fa {% if view_name == 'users:profile'  %} fa-user {% else %} fa-user-o {% endif %} fixed-plugin-button-nav cursor-pointer"></i>
              Личный кабинет
            </a>
          </li>
        {% endif %}
          <li class="nav-item dropdown pe-2 d-flex align-items-center">
            <a href="javascript:;"
               class="nav-link text-body p-0 d-flex align-items-center"
               id="dropdownMenuButton" data-bs-toggle="dropdown"
               aria-expanded="false">
              <i class="fa fa-bell cursor-pointer"></i>
              {% if notification|len_list > 0 %}
                <span class="badge bg-gradient-danger badge-circle text-xxs border-radius-2xl m-1 px-2">{{ notification|len_list }}</span>
              {% endif %}
            </a>
            <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4"
                aria-labelledby="dropdownMenuButton">
{#                          {% if view_name == 'crm:crm_customers' %}#}

              {% for n in notification %}
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="
/{{ n.content_object.get_my_model_name }}/{{ n.object_id }}/
">
                    <div class="d-flex py-1">
                      <div class="my-auto">
{#                        <img src="{% static "/assets/img/team-2.jpg" %}"#}
{#                             class="avatar avatar-sm   ">#}
                        {% if n.get_my_model_name == 'comment' %}
                        <i class="fa fa-envelope-o me-4 text-2xl"></i>
                        {% elif n.get_my_model_name == 'task' %}
                          <i class="fa fa-exclamation-triangle me-4 text-2xl"></i>
                        {% endif %}
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          {% if n.get_my_model_name == 'comment' %}
                          <span class="font-weight-bold">Новый комментарий</span>
                            {% elif n.get_my_model_name == 'task' %}
                            <span class="font-weight-bold">Новая задача</span>
                          {% endif %}
                          от {{ n.staff }}
                        </h6>
                        <p class="text-xs text-secondary mb-0 ">
                          {% if n.get_my_model_name == 'comment' %}
                          {{ n.text|slice:":30" }}...
                          {% elif n.get_my_model_name == 'task' %}
                          {{ n.task|slice:":30" }}...
                          {% endif %}
                          <br>
                          <i class="fa fa-clock me-1"></i>
                          {{ n.date }}
                        </p>
                      </div>
                    </div>
                  </a>
                <hr class="horizontal dark my-0">
                </li>

              {% endfor %}
              {#{% endif %}#}
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{#<script src="{% static "/pro/assets/js/core/popper.min.js" %}"></script>#}
{#<script src="{% static "/pro/assets/js/core/bootstrap.min.js" %}"></script>#}

{% endwith %}